spring:
  datasource:
    username: root
    password: Abcd123@
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/musicmemo?characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  session:
    jdbc:
      initialize-schema: always